# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20170725_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'Mes Stocks'},
        ),
    ]
