# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('taux', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom du produit')),
                ('marque', models.CharField(max_length=255, verbose_name='marque du produit')),
                ('price_HT', models.CharField(max_length=255, verbose_name='prix public HT')),
                ('price_TTC', models.CharField(max_length=255, verbose_name='prix public TTC')),
            ],
            options={
                'ordering': ['name', 'marque'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remise', models.IntegerField(verbose_name='remise en %')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Provider')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
