# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170515_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='remise',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='remise',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='remise',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_TTC',
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace',
            field=models.ManyToManyField(to='catalog.MarketPlace'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Provider'),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='name',
            field=models.CharField(choices=[('AMZ', 'Amazon'), ('EBY', 'Ebay'), ('WMT', 'Wallmart')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Remise',
        ),
    ]
