# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170706_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_HT',
            field=models.FloatField(verbose_name='prix public HT'),
        ),
    ]
