# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170706_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='remise',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
