# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170727_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='remise',
        ),
        migrations.AddField(
            model_name='product',
            name='remise',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='nbre_product',
            field=models.IntegerField(default=0),
        ),
    ]
